#!/bin/bash

# ALI Automation - Project Creator (IntelliJ + Java 11)
VERSION="1.0.0"

show_help() {
    cat << EOF
ALI Automation v${VERSION}

Usage: ali-automation create-project <PROJECT_NAME>

Commands:
    create-project <name>    Create a new IntelliJ-ready Gradle project
    version                  Show version information
    help                     Show this help message

Examples:
    ali-automation create-project MyTestProject
    ali-automation version
    ali-automation help
EOF
}

get_package_path() {
    local project_name="$1"

    echo "📦 Enter the package name for your project (e.g., com.i2c.automation.icm):"
    read -r user_package

    if [[ -z "$user_package" ]]; then
        echo "⚠️  No package provided. Using default: com.i2c.automation.aliapp"
        user_package="com.i2c.automation.aliapp"
    fi

    PACKAGE_PATH=$(echo "$user_package" | sed 's/\./\//g')
    PACKAGE_NAME="$user_package"

    echo "✅ Package set to: $PACKAGE_NAME"
    echo "📁 Source path: src/test/java/$PACKAGE_PATH/$project_name"
}

create_gradle_project() {
    GRADLE_VERSION="6.7"
    WORK_DIR="$(pwd)"  # ✅ create projects in user's current directory

    if [ -z "$1" ]; then
        echo "❌ Usage: ali-automation create-project <ProjectName>"
        exit 1
    fi

    PROJECT_NAME="$1"
    ROOT_DIR="$WORK_DIR"  # ✅ write to working dir, not brew dir

    read -r -d '' BUILD_GRADLE_CONTENT <<'EOF'
plugins {
    id 'java'
    id 'maven'
    id 'io.qameta.allure' version '2.8.1'
}

group 'SampleProject.generated'
version '1.0'

sourceCompatibility = 11
targetCompatibility = 11

test {
    useJUnitPlatform()
}

repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

jar {
    from sourceSets.test.output + sourceSets.test.allSource
    from { configurations.testRuntimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
}

compileTestJava.options.compilerArgs.add '-parameters'

def allureVersion = "2.13.6"
def junit5Version = "5.6.2"
allure {
    autoconfigure = true
    aspectjweaver = true
    version = allureVersion
    clean = true
    useJUnit5 { version = allureVersion }
}
dependencies {
    testImplementation("io.qameta.allure:allure-java-commons:$allureVersion")
    testImplementation("org.junit.jupiter:junit-jupiter-api:$junit5Version")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:$junit5Version")
    testImplementation("org.junit.jupiter:junit-jupiter-params:$junit5Version")
    implementation group: 'commons-io', name: 'commons-io', version: '2.11.0'
    implementation group: 'com.ibm.informix', name: 'jdbc', version: '4.50.9'
    implementation group: 'org.json', name: 'json', version: '20220924'
    implementation group: 'org.apache.commons', name: 'commons-csv', version: '1.9.0'
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.6.0'
    implementation fileTree(dir: '/Users/araza08/Data/i2c_Repos/Automation-ICM/Automation Migration/Utilities-JAR')
}
EOF

    if [ -z "$1" ]; then
        echo "❌ Usage: ali-automation create-project <ProjectName>"
        exit 1
    fi

    PROJECT_NAME="$1"
    get_package_path "$PROJECT_NAME"

    ROOT_DIR="$PROJECT_NAME"
    PROJECT_NAME_LOWER=$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]')
    SRC_MAIN_DIR="$ROOT_DIR/src/main/java/$PACKAGE_PATH"
    SRC_TEST_DIR="$ROOT_DIR/src/test/java/$PACKAGE_PATH/$PROJECT_NAME_LOWER"

    mkdir -p "$SRC_MAIN_DIR" "$SRC_TEST_DIR" "$ROOT_DIR/src/main/resources" "$ROOT_DIR/src/test/resources"

    SYSTEM_USER_NAME=$(git config user.name 2>/dev/null || echo "$USER")
    SYSTEM_USER_EMAIL=$(git config user.email 2>/dev/null || echo "eng.st14@i2cinc.com")
    GENERATED_DATE=$(date)

    echo "🚀 Creating Gradle project '$PROJECT_NAME'..."
    echo "$BUILD_GRADLE_CONTENT" > "$ROOT_DIR/build.gradle"
    echo "rootProject.name = '$PROJECT_NAME'" > "$ROOT_DIR/settings.gradle"

        # 🔖 Function to create Java files with header
    create_java_file() {
        local file_path="$1"
        local class_name="$2"
        local content="$3"

        cat > "$file_path" <<EOF
/**
 * This class was automatically generated by TestProject
 * Project: $PROJECT_NAME
 * Generated by: $SYSTEM_USER_NAME ($SYSTEM_USER_EMAIL)
 * Generated on $GENERATED_DATE.
 */
package $PACKAGE_NAME.$PROJECT_NAME_LOWER;

$content
EOF
    }

    # 🧩 ${PROJECT_NAME}.java
    create_java_file "$SRC_TEST_DIR/${PROJECT_NAME}.java" "$PROJECT_NAME" "$(cat <<EOF
import org.testng.Assert;
import io.qameta.allure.Allure;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.FileReader;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;

public class $PROJECT_NAME {
    public static WebDriver driver;

    @BeforeAll
    static void setup() throws Exception {
        System.setProperty("webdriver.chrome.driver", "/Users/araza08/Data/Libraries/chromedriver-mac-x64/chromedriver");
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("--remote-allow-origins=*", "ignore-certificate-errors");
        driver = new ChromeDriver(chromeOptions);
        driver.manage().timeouts().implicitlyWait(Duration.ofMillis(15000));
        driver.manage().window().maximize();
    }

    private static Object[][] provideParameters() throws Exception {
        List<${PROJECT_NAME}DataSource> csvList = new ArrayList<>();
        try (
            BufferedReader br = new BufferedReader(new FileReader("datasource/${PROJECT_NAME}_DataSource.csv"));
            CSVParser parser = CSVFormat.DEFAULT.withDelimiter(',').withHeader().parse(br);
        ) {
            for (CSVRecord record : parser) {
                ${PROJECT_NAME}DataSource csvObject = new ${PROJECT_NAME}DataSource();
                csvObject.TID = record.get("TC_ID");
                csvObject.Scenario_Description = record.get("Scenario_Description");
                csvObject.Application_URL = record.get("Application_URL");
                csvList.add(csvObject);
            }
            return csvList.stream()
                    .map(bean -> new Object[]{bean})
                    .toArray(Object[][]::new);
        }
    }

    @DisplayName("$PROJECT_NAME")
    @ParameterizedTest
    @MethodSource("provideParameters")
    void execute(${PROJECT_NAME}DataSource data) {
        try {
            // main logic
        } catch (Exception e) {
            data.Actual_Result = "Fail";
            Assert.fail("Fail: " + e.getMessage(), e);
        }
    }

    @AfterEach
    public void takeScreenShot() {
        Allure.attachment("Test End: ", new ByteArrayInputStream(((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES)));
    }

    @AfterAll
    static void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }
}
EOF
)"

    # 🧩 ${PROJECT_NAME}DataSource.java
    create_java_file "$SRC_TEST_DIR/${PROJECT_NAME}DataSource.java" "${PROJECT_NAME}DataSource" "$(cat <<EOF
public class ${PROJECT_NAME}DataSource {

    String TID;
    String Scenario_Description;
    String Module_Name;
    String Application_URL;
    String Verify_Login;
    String LoggedIn_UserID;
    String LoggedIn_UserPassword;
    String OLD_Password;
    String New_Password;
    String Confirm_NewPassword;
    String Expected_Result;
    String Actual_Result;
    String Test_Result;

    @Override
    public String toString() {
        return "[" + TID + ',' + Module_Name + ',' + Scenario_Description + ']';
    }
}
EOF
)"

    # 🧩 ${PROJECT_NAME}Screen.java
    create_java_file "$SRC_TEST_DIR/${PROJECT_NAME}Screen.java" "${PROJECT_NAME}Screen" "$(cat <<EOF
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

public class ${PROJECT_NAME}Screen {
    String oldPasswordFieldId = "old-password";
    String newPasswordFieldId = "new-password";
    String confirmNewPasswordFieldId = "confirm-password";
    String submitButtonId = "continueButton";

    private ${PROJECT_NAME}Screen() {}

    private static ${PROJECT_NAME}Screen instance = null;

    public static ${PROJECT_NAME}Screen getInstance() {
        if (instance == null) {
            instance = new ${PROJECT_NAME}Screen();
        }
        return instance;
    }

    public void execute(WebDriver driver, ${PROJECT_NAME}DataSource data) {
       driver.findElement(By.id(oldPasswordFieldId)).sendKeys(data.OLD_Password);
       driver.findElement(By.id(newPasswordFieldId)).sendKeys(data.New_Password);
       driver.findElement(By.id(confirmNewPasswordFieldId)).sendKeys(data.Confirm_NewPassword);
       driver.findElement(By.id(submitButtonId)).click();
    }
}
EOF
)"

    # 🧩 Navigation.java
    create_java_file "$SRC_TEST_DIR/Navigation.java" "Navigation" "$(cat <<EOF
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

public class Navigation {
    private static String User_Info_Button_Id = "user-info-drop";
    public static void selectUserInfoButton(WebDriver driver) throws Exception {
        By by = By.id(User_Info_Button_Id);
        driver.findElement(by).click();
        Thread.sleep(2000);
    }
}
EOF
)"

    # Create supporting folders
    mkdir -p "$ROOT_DIR/cleanup" "$ROOT_DIR/datasource"
    echo "-- SQL cleanup script for $PROJECT_NAME" > "$ROOT_DIR/cleanup/${PROJECT_NAME}_CleanUp.sql"
    echo "TC_ID,Scenario_Description,Application_URL" > "$ROOT_DIR/datasource/${PROJECT_NAME}_DataSource.csv"

    echo "🧩 Setting up Java 11 environment..."
    if ! brew list openjdk@11 &>/dev/null; then
        echo "📦 Installing Java 11..."
        brew install openjdk@11
    fi
    export JAVA_HOME="$(/usr/libexec/java_home -v 11)"
    export PATH="$JAVA_HOME/bin:$PATH"
    echo "✅ Java 11 active: $("$JAVA_HOME/bin/java" -version 2>&1 | head -n 1)"

    cd "$ROOT_DIR" || exit
    echo "🛠  Setting up Gradle wrapper version $GRADLE_VERSION..."
    mkdir -p gradle/wrapper
    cat <<EOF > gradle/wrapper/gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
EOF
    gradle wrapper --gradle-version $GRADLE_VERSION
    cat <<'EOS' > gradlew
#!/usr/bin/env sh
DIR="$(cd "$(dirname "$0")" && pwd)"
java -jar "$DIR/gradle/wrapper/gradle-wrapper.jar" "$@"
EOS
    chmod +x gradlew
    cd "$WORK_DIR"

    # IntelliJ configuration
    echo "🧩 Creating IntelliJ IDEA configuration..."
    
    # Create .idea directory structure
    mkdir -p "$ROOT_DIR/.idea"
    
    # Create modules.xml to register the project module
    cat > "$ROOT_DIR/.idea/modules.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ProjectModuleManager">
    <modules>
      <module fileurl="file://\$PROJECT_DIR\$/$PROJECT_NAME.iml" filepath="\$PROJECT_DIR\$/$PROJECT_NAME.iml" />
    </modules>
  </component>
</project>
EOF

    # Create misc.xml for project settings
    cat > "$ROOT_DIR/.idea/misc.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ProjectRootManager" version="2" languageLevel="JDK_11" default="true" project-jdk-name="11" project-jdk-type="JavaSDK">
    <output url="file://\$PROJECT_DIR\$/out" />
  </component>
</project>
EOF

    # Create vcs.xml for version control
    cat > "$ROOT_DIR/.idea/vcs.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="VcsDirectoryMappings">
    <mapping directory="" vcs="Git" />
  </component>
</project>
EOF

    # Create compiler.xml
    cat > "$ROOT_DIR/.idea/compiler.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CompilerConfiguration">
    <bytecodeTargetLevel target="11" />
  </component>
</project>
EOF

    # Create .iml file at the root level (not in subdirectory)
    IML_FILE="$PROJECT_NAME/$PROJECT_NAME.iml"
    cat > "$IML_FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://\$MODULE_DIR\$">
      <sourceFolder url="file://\$MODULE_DIR\$/src/main/java" isTestSource="false" />
      <sourceFolder url="file://\$MODULE_DIR\$/src/main/resources" type="java-resource" />
      <sourceFolder url="file://\$MODULE_DIR\$/src/test/java" isTestSource="true" />
      <sourceFolder url="file://\$MODULE_DIR\$/src/test/resources" type="java-test-resource" />
      <excludeFolder url="file://\$MODULE_DIR\$/.gradle" />
      <excludeFolder url="file://\$MODULE_DIR\$/build" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>
EOF

    echo "✅ Project '$PROJECT_NAME' created successfully!"
    echo "📁 Location: $(pwd)"
    echo "📦 Package: $PACKAGE_NAME.$PROJECT_NAME"
}

case "${1}" in
    create-project)
        if [ -z "$2" ]; then
            echo "❌ Project name is required"
            exit 1
        fi
        create_gradle_project "$2"
        ;;
    version)
        echo "ALI Automation v${VERSION}"
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        show_help
        ;;
esac
