#!/bin/bash

# ALI Automation - Project Creator
VERSION="1.0.0"

show_help() {
    cat << EOF
ALI Automation v${VERSION}

Usage: ali-automation create-project <PROJECT_NAME>

Commands:
    create-project <name>    Create a new Gradle project
    version                 Show version information
    help                    Show this help message

Examples:
    ali-automation create-project MyTestProject
    ali-automation version
    ali-automation help
EOF
}

get_package_path() {
    local project_name="$1"
    
    echo "📦 Please enter the package name for your project (e.g., com.i2c.automation.icm):"
    read -r user_package
    
    # Validate package name
    if [[ -z "$user_package" ]]; then
        echo "⚠️  No package provided. Using default: com.i2c.automation.aliapp"
        user_package="com.i2c.automation.aliapp"
    fi
    
    # Convert package to path (replace dots with slashes)
    PACKAGE_PATH=$(echo "$user_package" | sed 's/\./\//g')
    PACKAGE_NAME="$user_package"
    
    echo "✅ Package set to: $PACKAGE_NAME"
    echo "📁 Source path: src/test/java/$PACKAGE_PATH/$project_name"
}

create_gradle_project() {
    # ------------------ CONFIG ------------------
    GRADLE_VERSION="6.7"

    # 🧱 Your custom build.gradle content
    read -r -d '' BUILD_GRADLE_CONTENT <<'EOF'
plugins {
    id 'java'
    id 'maven'
    id 'io.qameta.allure' version '2.8.1'
}

group 'SampleProject.generated'
version '1.0'

test {
    useJUnitPlatform()
}

repositories {
    mavenCentral()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
}

jar {
    // Include compiled test classes and their sources
    from sourceSets.test.output+sourceSets.test.allSource

    // Collect and zip all classes from both test and runtime configurations
    from { configurations.testRuntimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
}

compileTestJava.options.compilerArgs.add '-parameters'

def allureVersion = "2.13.6"
def junit5Version = "5.6.2"
allure {
    autoconfigure = true
    aspectjweaver = true
    version = allureVersion

    clean = true

    useJUnit5 {
        version = allureVersion
    }
}
dependencies {
    testImplementation("io.qameta.allure:allure-java-commons:$allureVersion")
    testImplementation("org.junit.jupiter:junit-jupiter-api:$junit5Version")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:$junit5Version")
    testImplementation("org.junit.jupiter:junit-jupiter-params:$junit5Version")

    implementation group: 'commons-io', name: 'commons-io', version: '2.11.0'
    implementation group: 'com.ibm.informix', name: 'jdbc', version: '4.50.9'
    implementation group: 'org.json', name: 'json', version: '20220924'
    implementation group: 'org.apache.commons', name: 'commons-csv', version: '1.9.0'
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.6.0'
    implementation fileTree(dir: '/Users/araza08/Data/i2c_Repos/Automation-ICM/Automation Migration/Utilities-JAR')
}

EOF
    # ------------------ END CONFIG ------------------

    # ✅ Get project name
    if [ -z "$1" ]; then
        echo "❌ Usage: ali-automation create-project <ProjectName>"
        exit 1
    fi

    PROJECT_NAME="$1"
    
    # 🎯 Get package path from user
    get_package_path "$PROJECT_NAME"
    
    ROOT_DIR="$PROJECT_NAME"
    SRC_DIR="$ROOT_DIR/src/test/java/$PACKAGE_PATH/$PROJECT_NAME"

    # 🧑‍💻 Detect system user info
    SYSTEM_USER_NAME=$(git config user.name 2>/dev/null || echo "$USER")
    SYSTEM_USER_EMAIL=$(git config user.email 2>/dev/null || echo "eng.st14@i2cinc.com")
    GENERATED_DATE=$(date)

    echo "🚀 Creating Gradle project '$PROJECT_NAME'..."
    mkdir -p "$SRC_DIR"

    # 🧾 Write build.gradle
    echo "$BUILD_GRADLE_CONTENT" > "$ROOT_DIR/build.gradle"
    echo "✅ build.gradle created."

    # ⚙️ settings.gradle
    cat <<EOF > "$ROOT_DIR/settings.gradle"
rootProject.name = '$PROJECT_NAME'
EOF

    # 🔖 Function to create Java files with header
    create_java_file() {
        local file_path="$1"
        local class_name="$2"
        local content="$3"

        cat <<EOF > "$file_path"
/**
 * This class was automatically generated by TestProject
 * Project: $PROJECT_NAME
 * Generated by: $SYSTEM_USER_NAME ($SYSTEM_USER_EMAIL)
 * Generated on $GENERATED_DATE.
 */
package $PACKAGE_NAME.$PROJECT_NAME;

$content
EOF
    }

    # 🧩 $PROJECT_NAME.java
    create_java_file "$SRC_DIR/${PROJECT_NAME}.java" "$PROJECT_NAME" \
"import static io.qameta.allure.Allure.step;

import com.i2c.utils.LoginBean;
import org.testng.Assert;
import io.qameta.allure.Allure;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.FileReader;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;

public class $PROJECT_NAME {
    public static WebDriver driver;

    @BeforeAll
    static void setup() throws Exception {
        if (!isLoggedIn()) {
            System.setProperty(\"webdriver.chrome.driver\", \"/Users/araza08/Data/Libraries/chromedriver-mac-x64/chromedriver\");
            ChromeOptions chromeOptions = new ChromeOptions();
            chromeOptions.addArguments(\"--remote-allow-origins=*\", \"ignore-certificate-errors\");
            driver = new ChromeDriver(chromeOptions);
            driver.manage().timeouts().implicitlyWait(Duration.ofMillis(15000));
            driver.manage().window().maximize();
        }
    }

    private static Object[][] provideParameters() throws Exception {
        List<${PROJECT_NAME}DataSource> csvList = new ArrayList<>();
        try (
            BufferedReader br = new BufferedReader(new FileReader(\"datasource/${PROJECT_NAME}_DataSource.csv\"));
            CSVParser parser = CSVFormat.DEFAULT.withDelimiter(',').withHeader().parse(br);
        ) {
            for (CSVRecord record : parser) {
                ${PROJECT_NAME}DataSource csvObject = new ${PROJECT_NAME}DataSource();
                csvObject.TID = record.get(\"TC_ID\");
                csvObject.Scenario_Description = record.get(\"Scenario_Description\");
                csvObject.Application_URL = record.get(\"Application_URL\");
                csvList.add(csvObject);
            }
            return csvList.stream()
                    .map(bean -> new Object[]{bean})
                    .toArray(Object[][]::new);
        }
    }

    @DisplayName(\"$PROJECT_NAME\")
    @ParameterizedTest
    @MethodSource(\"provideParameters\")
    void execute(${PROJECT_NAME}DataSource data) {
        try {
            // main logic
        } catch (Exception e) {
            data.Actual_Result = \"Fail\";
            Assert.fail(\"Fail: \" + e.getMessage(), e);
        }
    }

    @AfterEach
    public void takeScreenShot() {
        Allure.attachment(\"Test End: \", new ByteArrayInputStream(((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES)));
    }

    @AfterAll
    static void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }
}
"

    # 🧩 ${PROJECT_NAME}DataSource.java
    create_java_file "$SRC_DIR/${PROJECT_NAME}DataSource.java" "${PROJECT_NAME}DataSource" \
"public class ${PROJECT_NAME}DataSource {

    String TID;
    String Scenario_Description;
    String Module_Name;
    String Application_URL;
    String Verify_Login;
    String LoggedIn_UserID;
    String LoggedIn_UserPassword;
    String OLD_Password;
    String New_Password;
    String Confirm_NewPassword;
    String Expected_Result;
    String Actual_Result;
    String Test_Result;

    @Override
    public String toString() {
        return \"[\" + TID + ',' + Module_Name + ',' + Scenario_Description + ']';
    }
}
"

    # 🧩 ${PROJECT_NAME}Screen.java
    create_java_file "$SRC_DIR/${PROJECT_NAME}Screen.java" "${PROJECT_NAME}Screen" \
"import com.i2c.addons.Informix.SendQuery;
import com.i2c.elements.ElementsUtility;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

public class ${PROJECT_NAME}Screen {
    String oldPasswordFieldId = \"old-password\";
    String newPasswordFieldId = \"new-password\";
    String confirmNewPasswordFieldId = \"confirm-password\";
    String submitButtonId = \"continueButton\";

    private ${PROJECT_NAME}Screen() {}

    private static ${PROJECT_NAME}Screen instance = null;

    public static ${PROJECT_NAME}Screen getInstance() {
        if (instance == null) {
            instance = new ${PROJECT_NAME}Screen();
        }
        return instance;
    }

    public void execute(WebDriver driver, ${PROJECT_NAME}DataSource data) {
       driver.findElement(By.id(oldPasswordFieldId)).sendKeys(data.OLD_Password);
       driver.findElement(By.id(newPasswordFieldId)).sendKeys(data.New_Password);
       driver.findElement(By.id(confirmNewPasswordFieldId)).sendKeys(data.Confirm_NewPassword);
       driver.findElement(By.id(submitButtonId)).click();
    }
}
"

    # 🧩 Navigation.java
    create_java_file "$SRC_DIR/Navigation.java" "Navigation" \
"import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

public class Navigation {
    private static String User_Info_Button_Id = \"user-info-drop\";
    public static void selectUserInfoButton(WebDriver driver) throws Exception {
        By by = By.id(User_Info_Button_Id);
        driver.findElement(by).click();
        Thread.sleep(2000);
    }
}
"

    # 📂 Add cleanup + datasource folders
    mkdir -p "$ROOT_DIR/cleanup"
    mkdir -p "$ROOT_DIR/datasource"

    # 🗂️ Create files inside them
    echo "-- SQL cleanup script for $PROJECT_NAME" > "$ROOT_DIR/cleanup/${PROJECT_NAME}_CleanUp.sql"
    echo "DataSource file created at " > "$ROOT_DIR/datasource/${PROJECT_NAME}_DataSource.csv"

        # ⚙️ Add Gradle wrapper
    cd "$ROOT_DIR"

    # 🧩 Force Gradle 6.7 wrapper without relying on system Gradle
    echo "🛠  Setting up Gradle wrapper version $GRADLE_VERSION..."

    # Create gradle/wrapper directory
    mkdir -p gradle/wrapper

    # Write the gradle-wrapper.properties file manually
    cat <<EOF > gradle/wrapper/gradle-wrapper.properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
EOF

    # Download Gradle 6.7 binary zip (not jar)
    echo "⬇️  Downloading Gradle ${GRADLE_VERSION}..."
    curl -sLo gradle-${GRADLE_VERSION}-bin.zip https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip

    # Extract wrapper jar from the zip
    unzip -q gradle-${GRADLE_VERSION}-bin.zip "gradle-${GRADLE_VERSION}/lib/gradle-wrapper.jar" -d temp_gradle
    mv temp_gradle/gradle-${GRADLE_VERSION}/lib/gradle-wrapper.jar gradle/wrapper/
    rm -rf temp_gradle gradle-${GRADLE_VERSION}-bin.zip

    # Create gradlew launcher script
    cat <<'EOS' > gradlew
#!/usr/bin/env sh
DIR="$(cd "$(dirname "$0")" && pwd)"
java -jar "$DIR/gradle/wrapper/gradle-wrapper.jar" "$@"
EOS
    chmod +x gradlew

    echo "✅ Gradle wrapper locked to version $GRADLE_VERSION."

    echo "✅ Project '$PROJECT_NAME' created successfully!"
    echo "📁 Location: $(pwd)/$ROOT_DIR"
    echo "📦 Package: $PACKAGE_NAME.$PROJECT_NAME"
}

# Main command handler
case "${1}" in
    create-project)
        if [ -z "$2" ]; then
            echo "❌ Project name is required"
            echo "Usage: ali-automation create-project <PROJECT_NAME>"
            exit 1
        fi
        create_gradle_project "$2"
        ;;
    version)
        echo "ALI Automation v${VERSION}"
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        if [ -z "$1" ]; then
            show_help
        else
            echo "❌ Unknown command: $1"
            show_help
            exit 1
        fi
        ;;
esac
